services:
  - docker

script:
  - docker run
    -d
    --name=database
    -e MYSQL_ROOT_PASSWORD=123456
    --tmpfs=/var/lib/mysql/:rw,noexec,nosuid,size=600m
    --tmpfs=/tmp/:rw,noexec,nosuid,size=50m mysql:5.6 &&

    docker run
    --link database:database
    -v $(pwd):/repo
    -e CI=true
    -e TEST_DB_HOST=database
    -e TEST_DB_PORT=3306
    -e BRANCH=$TRAVIS_BRANCH
    -e COMMIT_ID=$TRAVIS_COMMIT
    -e IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    -e AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY
    --env-file <(env | grep ^ENC_PASS_)
    --env-file <(env | grep ^TRAVIS_)
    -e TRAVIS_BUILD_DIR=/repo
    hollowverse/build-env

notifications:
  email: false

